# Generated by Django 6.0.1 on 2026-04-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_type',
            field=models.CharField(choices=[('shoe_size', 'Pointure chaussure'), ('clothing_size', 'Taille vêtement'), ('color', 'Couleur'), ('capacity', 'Capacité'), ('unique', 'Unique')], default='shoe_size', max_length=30),
        ),
        migrations.AddField(
            model_name='size',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
