# Generated by Django 6.0.1 on 2026-04-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_variant_type_size_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='value',
        ),
        migrations.AlterField(
            model_name='size',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
