# Generated by Django 6.0.1 on 2026-01-25 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('received', 'Commande reçue'), ('preparing', 'Préparation'), ('shipped', 'Expédiée'), ('delivered', 'Livrée')], default='received', max_length=20)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=80)),
                ('quarter', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('pay_method', models.CharField(default='MTN Mobile Money', max_length=80)),
                ('shipping_fee', models.PositiveIntegerField(default=0)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40)),
                ('product_name', models.CharField(max_length=200)),
                ('size_value', models.PositiveSmallIntegerField()),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('line_total', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.variant')),
            ],
        ),
    ]
