# Generated by Django 6.0.1 on 2026-02-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mode',
            field=models.CharField(default='retail', max_length=20),
        ),
    ]
