# Generated by Django 6.0.1 on 2026-03-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_state',
            field=models.CharField(choices=[('unpaid', 'Non payé'), ('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué')], default='unpaid', max_length=20),
        ),
    ]
