# Generated by Django 6.0.1 on 2026-05-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size_value',
            field=models.CharField(max_length=50),
        ),
    ]
